"""
Django settings for v1 project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[]
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

DEBUG = env("DEBUG")

AUTH_USER_MODEL = "hub.User"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "hub.apps.HubConfig",
    'oauth2_provider',
    'library',
    'blog',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'allauth',
    'allauth.account',
    "allauth.socialaccount",
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]



ROOT_URLCONF = 'v1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'v1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": env(
            "SQLITE_PATH",
            default=str(BASE_DIR / "db.sqlite3")
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(
    env(
        "MEDIA_ROOT",
        default=str(BASE_DIR / "media")
    )
)

LOGIN_URL = "hub:login"
LOGIN_REDIRECT_URL = "hub:home"
LOGOUT_REDIRECT_URL = "hub:home"

SESSION_COOKIE_AGE = 900


APP_BASE_URL = env(
    "APP_BASE_URL",
    default="http://127.0.0.1:8000"
)

HUB_AUTHORIZE_URL = f"{APP_BASE_URL}/o/authorize/"
HUB_TOKEN_URL = f"{APP_BASE_URL}/o/token/"
HUB_REVOKE_TOKEN_URL = f"{APP_BASE_URL}/o/revoke_token/"

LIBRARY_CLIENT_ID = env("LIBRARY_CLIENT_ID")
LIBRARY_CLIENT_SECRET = env("LIBRARY_CLIENT_SECRET")
BLOG_CLIENT_ID = env("BLOG_CLIENT_ID")
BLOG_CLIENT_SECRET = env("BLOG_CLIENT_SECRET")
HUB_CONTEXT_PROFILE_URL = (f"{APP_BASE_URL}/hub/api/v1/context-profile/")

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 60,
    "REFRESH_TOKEN_EXPIRE_SECONDS": 60 * 60 * 24 * 15,  # 15 days
    "SCOPES": {
        "contextual_profile:read": "Read access to contextual profiles"
        },
    "DEFAULT_SCOPES": [],
    "ERROR_RESPONSE_WITH_SCOPES": True,
}


OAUTH2_PROVIDER_APPLICATION_MODEL = "oauth2_provider.Application"

LIBRARY_REDIRECT_URI = ( f"{APP_BASE_URL}/library/oauth/callback/")
BLOG_REDIRECT_URI = (f"{APP_BASE_URL}/blog/oauth/callback/")

CORS_ORIGIN_ALLOW_ALL = True


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "EXCEPTION_HANDLER": "hub.exceptions.custom_exception_handler",
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CM3070 - Final Project: IL-Hub Contextual Profile API',
    'DESCRIPTION': 'API for contextual profile retrieval in federated systems',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'oauth2': {
                'type': 'oauth2',
                'flows': {
                    'authorizationCode': {
                        'authorizationUrl': '/o/authorize/',
                        'tokenUrl': '/o/token/',
                        'scopes': {
                            'contextual_profile:read': 'Read contextual profiles',
                        },
                    },
                },
            },
        },
    },
    
}

AUDIT_LOG_DIR = Path(
    env(
        "AUDIT_LOG_DIR",
        default=str(BASE_DIR / "logs")
    )
)
AUDIT_LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "audit_json": {
            "()": "hub.logging_services.formatters.GdprLogJsonFormatter",
        },
    },

    "handlers": {
        "audit_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "INFO",
            "filename": f"{AUDIT_LOG_DIR}/gdpr_logs.jsonl",
            "maxBytes": 1048756,
            "backupCount": 2,
            "encoding": "utf-8",
            "formatter": "audit_json",
        },
    },

    "loggers": {
        "ilhub.gdpr": {
            "handlers": ["audit_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
        "EMAIL_AUTHENTICATION": True,
    }
}
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_LOGIN_METHODS = {'email'}
SOCIALACCOUNT_ONLY = False
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
ACCOUNT_ADAPTER = "hub.adapters.ExistingUserAccountAdapter"
SOCIALACCOUNT_ADAPTER = "hub.adapters.ExistingUserSocialAccountAdapter"
