# Generated by Django 6.0.4 on 2026-07-08 02:09

import django.db.models.deletion
import hub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryInterestTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to=hub.models.profile_photo_uuid)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_context', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(to='hub.blogtopics')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to=hub.models.profile_photo_uuid)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_context', to=settings.AUTH_USER_MODEL)),
                ('interest_topics', models.ManyToManyField(to='hub.libraryinteresttopics')),
            ],
        ),
    ]
