# Generated by Django 6.0.4 on 2026-07-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_blogtopics_libraryinteresttopics_blogcontext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontext',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogcontext',
            name='topics',
            field=models.ManyToManyField(blank=True, to='hub.blogtopics'),
        ),
        migrations.AlterField(
            model_name='librarycontext',
            name='interest_topics',
            field=models.ManyToManyField(blank=True, to='hub.libraryinteresttopics'),
        ),
        migrations.AlterField(
            model_name='librarycontext',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
