# Generated by Django 6.0.4 on 2026-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_blogcontext_nickname_alter_blogcontext_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
