# Generated by Django 6.0.4 on 2026-07-15 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_user_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
