# Generated by Django 6.0.4 on 2026-07-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_alter_user_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontext',
            name='photo_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
