# Generated by Django 6.0.4 on 2026-07-17 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_clientregistry'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistry',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_configuration', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
