# Generated by Django 6.0.4 on 2026-07-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_alter_clientregistry_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientregistry',
            name='client_name',
        ),
    ]
