# Generated by Django 6.0.4 on 2026-08-05 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_remove_clientregistry_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
