# Generated by Django 6.0.4 on 2026-08-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_remove_user_bio_user_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
        migrations.AddField(
            model_name='user',
            name='gdpr_notice_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gdpr_notice_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
