# Generated by Django 6.0.4 on 2026-08-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_remove_user_first_login_user_gdpr_notice_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gdpr_notice_accepted',
            new_name='privacy_notice_accepted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gdpr_notice_accepted_at',
            new_name='privacy_notice_accepted_at',
        ),
    ]
